Repository cyberway/golos.contracts, pull requests merged in 2019-06, with the labels that each got.

#708 Fix vesting withdraw: erase objects with too low amount #706
  golos.vesting/golos.vesting.cpp
Labels: bug

#712 Optimize pay_curators #653
  golos.publication/golos.publication.abi
  golos.publication/golos.publication.cpp
  golos.publication/objects.hpp
Labels: Medium

#716 Add reward_event to posts #702
  docs/ru-RU/golos.publication_contract.md
  golos.publication/golos.publication.abi
  golos.publication/golos.publication.cpp
  golos.publication/golos.publication.hpp
  golos.publication/objects.hpp
Labels: High

#733 Change type for gls.vesting:stat event #732
  golos.vesting/golos.vesting.abi
Labels: High, bug

#736 Rewrite withdraw loop so all erase/inc in one place #730
  golos.vesting/golos.vesting.cpp
Labels: bug

#742 Allow to un-delegate to 0 remainder #741
  golos.vesting/golos.vesting.cpp
  tests/golos.vesting_tests.cpp
Labels: bug

#743 Forbid withdraw vesting with no token balance #731
  golos.vesting/golos.vesting.cpp
  tests/golos.vesting_tests.cpp
Labels: bug

#746 Fix curator reward in postreward event #740
  golos.publication/golos.publication.abi
  golos.publication/golos.publication.cpp
  golos.publication/golos.publication.hpp
  golos.publication/objects.hpp
Labels: bug

#745 Limit vesting retire by amount scheduled to withdraw #729
  golos.charge/golos.charge.cpp
  golos.vesting/golos.vesting.cpp
  golos.vesting/golos.vesting.hpp
  tests/golos.vesting_tests.cpp
Labels: bug
